// Do not edit this file.
// This hands-on introduces a technique to speed up without changing.

function wait(m) {
    const d1 = new Date();
    while (true) {
      const d2 = new Date();
      if (d2 - d1 > m) {
        break;
      }
    };
}

wait(100);

function insertText(text, target) {
    document.getElementById(target).textContent = text;
}

window.addEventListener("load", function() {
    var text = "Completed!";
    insertText(text, "js-check");
});
